### PR TITLE
Fix #17

### LINKED ISSUE #17: [Feature] Add Browser-update.org Banner
Notify visitors to update their browser to the latest version. https://browser-update.org

```
<script> 
var $buoop = {required:{e:-1,f:-1,o:-1,s:-1,c:-1},insecure:true,api:2020.03 }; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

### PR DESCRIPTION
**Pull request by ssteigen**
Will notify users with browsers more than 1 version behind the latest.

@eugeneration let me know if you would like to support more versions than that.

### CODE REVIEW

**Comment by eugeneration** [comment]
This looks like a good utility to add - some people have been complaining the site isn't working for them and it could be a browser incompatibility issue.

I feel like 1 version could be a little strict, is that typical practice? If one version is the usual thing people do then I'd be fine merging this

**Comment by FlynnFarrow** [comment]
I feel like 1 version is strict too. Works on Edge Chromium 80 but not IE11.

**Comment by FlynnFarrow** [comment]
It's easy to use too, I've added it to my fork at https://flynnfarrow.github.io/HappyIslandDesigner. It'll show up for anything under Edge Chromium 79 in the IE/Edge category, etc, you can see all the compatible browsers by looking at my code [here](https://github.com/FlynnFarrow/HappyIslandDesigner/blob/master/index.html). Scroll down to line 35 to see the code.

**Comment by eugeneration** [comment]
Hey @ssteigen - could you update your PR to have the values FlynnFarrow had? I feel people might get incorrectly blocked from using the app if it is just a single version behind.

**Comment by ssteigen** [comment]
No problem. Done.

**Comment by eugeneration** [comment]
Thanks @ssteigen  and @FlynnFarrow for this!

**Pull request merged**
