### PR TITLE
feat: Typescript rewrite

### PR DESCRIPTION
**Pull request by bodinsamuel**
Hey,

I saw your amazing project on twitter today ! ❤️ (well it was today few hours ago)
**I wanted to contribute**, especially for the screenshot loading but I found it a bit complicated to contribute with the codebase in this current shape.

This is a purely personal initiative, I'm not pushing anything to you. It's just a more modern way to write it, but nothing against your way of doing it ☺️ 

I just wanted to share this with you, I don't expect this PR to be "reviewable" as it is a complete rewrite to Typescript + npm. If you are interested to know more or even want to merge, I'll be happy to this discuss. **Otherwise feel free to entirely dismiss this PR 👍** 

Right now, I only put 3hours of work so it's **not yet complete.** There is a few gotchas, especially when executing paperjs outside of their controlled environnement (e.g: some automatic functions are not there like math between point, global variables etc...)
But I made it run almost entirely 🤩

Screenshot 2020-03-31 02 26 50

## Running

```bash
# install the dependencies
yarn

# launch the dev server with hot reload
yarn dev
```

go to: http://localhost:8080/

### CODE REVIEW

**Comment by eugeneration** [comment]
wow if you could get this to completely work it would be a real life saver in terms of project organization. I keep pushing off switching to a real development environment and it only keeps becoming an increasingly daunting task to do, but it looks like you've done all of the heavy lifting here!

I've had bad times setting up yarn/npm for projects which is why I was so hesitant here

**Comment by eugeneration** [comment]
Also are you the one who DMed me on reddit about working on the screenshot conversion feature?

**Comment by bodinsamuel** [comment]
> I've had bad times setting up yarn/npm for projects which is why I was so hesitant here

Maybe I can help answer your question if you have any ☺️ 

> Also are you the one who DMed me on reddit about working on the screenshot conversion feature?

Nope, but I guess many people would love this 👍 

--- 

If you are interested in merging, then I can continue to update this PR. That would make merging a bit complicated with other PRs though.

**Comment by eugeneration** [comment]
The other PRs that are coming in shouldn't be too hard to redo

**Comment by FlynnFarrow** [comment]
@bodinsamuel as the tool doesn't work in some browsers, could you add the browser-update script maybe? And could you add templates. I'm also currently working on an Android application for the tool and I want to merge a island name generator tool that I forked too.

**Comment by bodinsamuel** [comment]
I'm in the process of solving the last few issues. I should have done it in multiple steps but got carried away :3 I hope to be done by the end of the day, hopefully 🤞

**Comment by FlynnFarrow** [comment]
Also I should say we need you to add some assets like in #21

**Comment by FlynnFarrow** [comment]
image
This is what my repo looks like rn

**Comment by FlynnFarrow** [comment]
Gonna add a link to my island name generator soon to mine.

**Comment by FlynnFarrow** [comment]
I think we would work good together but problem is I've never used typescript...

**Comment by eugeneration** [comment]
Hey FlynnFarrow, the features you mentioned shouldn't be tacked onto this commit, they should be committed as commits on top of this. Adding too much into one commit makes history messy. Also, typescript is a superset of javascript, so if you can write javascript you can write typescript.

The browser update script also only affects index.html so it shouldn't conflict (much) with this commit.

**Comment by FlynnFarrow** [comment]
> Adding too much into one commit makes history messy. 

Yeah I get ya @eugeneration and the script only affects that, and you don't have to put the features in the whole thing, you could link to them like you link to your Twitter.

**Comment by eugeneration** [comment]
@bodinsamuel  btw I will be landing another major change to the site, but don't let that stop you from working on this. I can redo my work on top of this commit (I would probably merge it into a separate branch that I can later merge into master once it reaches feature parity)

**Comment by bodinsamuel** [comment]
@eugeneration Thanks for letting me know (and congrats on shipping this !).
I got hit by a few blockers than I can not fix right now:
- Drawing pixels are not correct, not sure why
- Can not paint over layers that are above (e.g: picking sand can no longer paint over layer1) 
- Can not place item in the map

I'm happy that I managed to fix most of the remaining bugs this weekend, it was challenging but learn a lot. Unfortunately the remaining ones are quite important 🙇‍♂️
If you want to help, please feel free to edit the branch as you should be able to do (I think).

**Comment by bodinsamuel** [comment]
🤯you are a beast

**Comment by eugeneration** [comment]
Haha here goes nothing

**Comment by bodinsamuel** [comment]
❤️

**Pull request merged**
