### PR TITLE
Add Template modal (and the first React components!)

### PR DESCRIPTION
**Pull request by eugeneration**
Adds about 20% of the total map templates. Includes a highly visible way to encourage people (who speak english) to send in more maps

### CODE REVIEW

**Comment by acyroen** [comment]
HappyIslandDesigner_1592888106994

hope it will help - supporter from france

**Comment by CaptainReina** [comment]
HappyIslandDesigner_1609747565993

hope it helps!

**Comment by Togekiss** [comment]
almond base
thank you for this amazing app!

**Comment by MarissaBlackwing** [comment]
HappyIslandDesigner_1660294643927
Here's a recreated map.

**Pull request merged**
